title: Capsis Finance
description: Crypto Trading
theme: just-the-docs

url: https://capsis-finance.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
