
services:
  capsis_jekyll:
    container_name: "capsis_jekyll"
    image: capsis-jekyll/doc:0.0.0
    user: "1000:1000"
    build:
      context: ./
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
#    stdin_open: true
#    tty: true
    command: bundle exec jekyll serve -H 0.0.0.0 -t
